version: '3.8'

services:
  sonarqube-front:
    image: sonarqube:community 
    container_name: sonar-front-analysis
    ports:
      - "9001:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_front_data:/opt/sonarqube/data
      - sonar_front_extensions:/opt/sonarqube/extensions
      - sonar_front_logs:/opt/sonarqube/logs
    restart: no

volumes:
  sonar_front_data:
  sonar_front_extensions:
  sonar_front_logs: 
